image:
  file: .devcontainer/Dockerfile

tasks:
  - init: pip install -r requirements.txt
  - init: bash .devcontainer/onCreateCommand.sh
    command: bash .devcontainer/postStartCommand.sh && bash && exit

vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools-driver-pg
    - mtxr.sqltools
